In [16]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [6]:
dt = pd.read_csv('data.csv')
dt = pd.DataFrame(dt)

In [7]:
dt = pd.read_csv('data.csv')
dt = pd.DataFrame(dt, columns=['MCB', 'Ngày công bố', 'Nhóm tuổi', 'G-Related-Cases', 'Ngày khởi phát', 'Họ và tên'])

In [8]:
dt

,MCB,Ngày công bố,Nhóm tuổi,G-Related-Cases,Ngày khởi phát,Họ và tên
0,BN416,25/07/2020,3.Từ 41-60,0,17/07/2020,Trần Văn Dũng
1,BN418,26/07/2020,4.Trên 60,0,11/07/2020,Nguyễn Văn Nam
2,BN419,26/07/2020,1.Dưới 18,0,20/07/2020,Ngô Bùi Trương Vũ
3,BN420,26/07/2020,4.Trên 60,0,12/07/2020,Phạm Thị Bích Phương
4,BN421,27/07/2020,2.Từ 18-40,0,23/07/2020,Lê Đình Huy
...,...,...,...,...,...,...
384,BN842,10/08/2020,1.Dưới 18,BN774,26/7/2020,Nguyễn Nhật Minh
385,BN843,10/08/2020,4.Trên 60,BN800,NaN,Trần Thị Nga
386,BN844,10/08/2020,2.Từ 18-40,BN845,NaN,Nguyễn Thị Diễm Phương
387,BN845,10/08/2020,2.Từ 18-40,BN844,NaN,Hoàng Thị Tâm Thư
388,BN846,10/08/2020,1.Dưới 18,0,NaN,Trần Trung Khánh

In [40]:
end_node = list(dt['MCB'])
name = list(dt['Họ và tên'])
group = map(lambda x: x.split('.')[0], list(dt['Nhóm tuổi']))
ngay_cong_bo = list(dt['Ngày công bố'])
start_date = list(dt['Ngày khởi phát'])
start_node = list(dt['G-Related-Cases'])

In [41]:
for i in range(len(ngay_cong_bo)):
    if pd.isna(start_date[i]):
        d = datetime.strptime(ngay_cong_bo[i], '%d/%m/%Y')
        start_date[i] = d - timedelta(days=5)
        ngay_cong_bo[i] = datetime.strptime(ngay_cong_bo[i], '%d/%m/%Y')
    else:
        try:
            start_date[i] = datetime.strptime(start_date[i], '%d/%m/%Y')
            ngay_cong_bo[i] = datetime.strptime(ngay_cong_bo[i], '%d/%m/%Y')
        except:
            pass

In [42]:
start_date

[datetime.datetime(2020, 7, 17, 0, 0),
 datetime.datetime(2020, 7, 11, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 12, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 18, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 18, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 16, 0, 0),
 datetime.datetime(2020, 7, 6, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 18, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 21, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 18, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 5, 0, 0),
 datetime.datetime(2020, 7, 21, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 28, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 20, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 7, 29, 0, 0),
 datetime.datetime(2020, 7, 19, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 7, 22, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 7, 31, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 7, 24, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 7, 21, 0, 0),
 datetime.datetime(2020, 7, 25, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 5, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 8, 2, 0, 0),
 datetime.datetime(2020, 7, 23, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 8, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 7, 30, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 8, 3, 0, 0),
 datetime.datetime(2020, 7, 21, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 6, 0, 0),
 datetime.datetime(2020, 7, 27, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 8, 4, 0, 0),
 datetime.datetime(2020, 7, 26, 0, 0),
 datetime.datetime(2020, 8, 5, 0, 0),
 datetime.datetime(2020, 8, 5, 0, 0),
 datetime.datetime(2020, 8, 5, 0, 0),
 datetime.datetime(2020, 8, 5, 0, 0)]

In [43]:
graph = {}
for s, t ,g, d, b, n in zip(end_node, start_node, group, start_date, ngay_cong_bo, name):
    t = t.replace(" ","")
    graph[s] = [t.split(','), g, d, b, n]

In [44]:
len(graph)

389

In [49]:
rela = []
for src in graph.keys():
    t = graph[src]
    for i in range(len(t[0])):
        rela.append([t[0][i], src, t[1], t[2], t[3], t[4]])

In [53]:
t = pd.DataFrame(rela, columns=['source', 'target','age_group', 'onset_date', 'announce_date', 'name'])

In [54]:
t.to_csv('relation_new.csv')

In [55]:
t

    source target age_group onset_date announce_date                    name
0        0  BN416         3 2020-07-17    2020-07-25           Trần Văn Dũng
1        0  BN418         4 2020-07-11    2020-07-26          Nguyễn Văn Nam
2        0  BN419         1 2020-07-20    2020-07-26       Ngô Bùi Trương Vũ
3        0  BN420         4 2020-07-12    2020-07-26    Phạm Thị Bích Phương
4        0  BN421         2 2020-07-23    2020-07-27             Lê Đình Huy
..     ...    ...       ...        ...           ...                     ...
681  BN774  BN842         1 2020-07-26    2020-08-10        Nguyễn Nhật Minh
682  BN800  BN843         4 2020-08-05    2020-08-10            Trần Thị Nga
683  BN845  BN844         2 2020-08-05    2020-08-10  Nguyễn Thị Diễm Phương
684  BN844  BN845         2 2020-08-05    2020-08-10       Hoàng Thị Tâm Thư
685      0  BN846         1 2020-08-05    2020-08-10        Trần Trung Khánh

[686 rows x 6 columns]